# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

generic-y += bpf_perf_event.h
generic-y += msgbuf.h
generic-y += poll.h
generic-y += shmbuf.h

generated-y += unistd_32.h
generated-y += unistd_64.h
generated-y += unistd_x32.h
